### ISSUE TITLE
Ender 5 upgrade

### ISSUE THREAD

**Issue by MadeInRu** [FYSETC/FYSETC-S6#15]
Dear Fysetc guys,

Can you please assists me. I've ordered your motherboard S6 V2.0 in order to upgrade my Ender 5, and want to know if i connected all the jumpers correctly. Please see the picture.  

Also I've ordered TMC 2226 drivers, are they compatible with that motherboard?

Which parts of the software i need to adjust for Ender 5?

With best regards,

Jevgeni
![IMG_20210227_201312](https://user-images.githubusercontent.com/79577409/109397964-faa2c480-7939-11eb-82bf-ce80858da338.jpg)

**Comment by GerogeFu** [comment]
I don't think so , the jumpers for stepper driver are not right.
![image](https://user-images.githubusercontent.com/7496375/119918947-f5d2c880-bf9b-11eb-9685-16480994bddd.png)
You can check the README here: https://github.com/FYSETC/FYSETC-S6
![image](https://user-images.githubusercontent.com/7496375/119919010-18fd7800-bf9c-11eb-9ee0-6f58ea7f9340.png)
