### ISSUE TITLE
New bootloader

### ISSUE THREAD

**Issue by GMagician** [FYSETC/FYSETC-S6#19]
Hi, not sure this is the right place.
I tryed to upload new bootloader 0x8000 with stcube.
Once loaded, always with dfu and VScode I uploaded Marlin S6_8000 env but once I reboot (boot jumper and power off/on) no usb port happears.

Since it doesn't work I re uploaded boot_10000 and marlin s6 env and it works.

What's wrong?

**Comment by GMagician** [comment]
Precompiled Marlin, loaded with stcube, works. Only the source with vscode seems to hang.
I wrote to Marlin github

**Comment by GerogeFu** [comment]
Did you try the branch in this repo, and what upstream Marlin are you using? The right one should be bugfix-2.0.x.

**Comment by GMagician** [comment]
Marlin in this repo is working, I tryed the very last bugfix in Marlin, compiled for 8000 env, that seems not to work

**Comment by GerogeFu** [comment]
Did you raise an issue for Marlin ?

**Comment by GMagician** [comment]
I wrote on PR which merged 8000 version, but I think it's good to open an issue

**Comment by kyon03** [comment]
same issue whats the solution?

**Comment by rsdcampos** [comment]
Same issue for me to. If I use the 0x10000 the eeprom don't save the changes, when I do a M500 it returns "Error writing to EEPROM" and EEPROM datasize error". There are any solution for it?

**Comment by GerogeFu** [comment]
Check the PR here https://github.com/MarlinFirmware/Marlin/pull/22421

**Comment by rsdcampos** [comment]
> 
> 
> Check the PR here [MarlinFirmware/Marlin#22421](https://github.com/MarlinFirmware/Marlin/pull/22421)

Nope, I made your changes in Marlin bugfix and used your entire commit using my configurations files without sucess in both, same issue. Just for complete answer, yes, I changed the envs in platformio.ini and tryed both variants without sucess.

**Comment by GerogeFu** [comment]
Now should work. Check the [PR](MarlinFirmware/Marlin#22421) there.

**Comment by GMagician** [comment]
Yep that solve this
