### ISSUE TITLE
FYSETC S6 2.0 and TMC2209V3.1 - TMC CONNECTION ERROR

### ISSUE THREAD

**Issue by Leidge** [FYSETC/FYSETC-S6#38]
I have the FYSETC S6 2.0 card and I'm trying to use the TMC2209 V3.1 driver
I'm using the FYSETC MINI 12864 V2.1 panel with SDCARD.
The TMC CONNECTION ERROR message appears on the panel when I turn on the card.

I'm trying to test the engines with Marlin BUGFIX 2.0 and 2.1.
It is returning the same error.

I always get the message 'TMC CONNECTION ERROR'.
Even if I put it in the 24v source with the pins in DC5V or in the USB.
Even if I put the pin on 5V and DC5V.

I'm trying to run TMC2209 V3.1 in UART.
![image](https://user-images.githubusercontent.com/4392926/187251969-5ecad9e3-9fa9-4fe8-b9d2-79262867b03e.png)

**Comment by igor-arkhipov** [comment]
Any solution @Leidge?
