### ISSUE TITLE
Please tell me the pin number of the FFC connector.

### ISSUE THREAD

**Issue by myunchulshin** [FYSETC/FYSETC-S6#9]
![Screenshot 2020-08-07 at 13 06 45](https://user-images.githubusercontent.com/69189880/89608114-2af81800-d8af-11ea-835b-76498b5e705d.jpg)

Top right of the board

Please tell me the pin number of the FFC connector

**Comment by GerogeFu** [comment]
You can see in PCB  file.
![image](https://user-images.githubusercontent.com/7496375/89620261-ffcaf400-d8c1-11ea-9d81-0d4f6f16693a.png)

**Comment by GerogeFu** [comment]
![image](https://user-images.githubusercontent.com/7496375/89620406-2b4dde80-d8c2-11ea-9ea7-63a35c870f09.png)

**Comment by myunchulshin** [comment]
Thank you
